[package]
name = "emukc"
version = "0.1.0"
edition = "2021"
categories = ["emulator"]
description = "A simple emulator for the web browser game: Kantai Collection"
exclude = ["z/", ".github/", "crates/"]
homepage = "https://github.com/master-g/emukc.git"
keywords = ["emulator", "kancolle"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/master-g/emukc"
rust-version = "1.81.0"

[workspace]
exclude = ["benches"]
members = ["crates/*"]

[workspace.lints.clippy]
type_complexity = "allow"
doc_markdown = "warn"
manual_let_else = "warn"
undocumented_unsafe_blocks = "warn"
redundant_else = "warn"
match_same_arms = "warn"
semicolon_if_nothing_returned = "warn"
redundant_closure_for_method_calls = "warn"
unwrap_or_default = "warn"

ptr_as_ptr = "warn"
ptr_cast_constness = "warn"
ref_as_ptr = "warn"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"
missing_docs = "warn"
unsafe_code = "deny"

[lints]
workspace = true

[features]
dynamic_linking = ["dep:emukc_dylib"]

[dependencies]
emukc_internal = { path = "crates/emukc_internal" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
emukc_dylib = { path = "crates/emukc_dylib", optional = true }

[workspace.dependencies]
anyhow = "1.0.89"
async-trait = "0.1"
base16ct = { version = "0.2.0", features = ["alloc"] }
bcrypt = { version = "0.15.1" }
bs58 = { version = "0.5.1" }
chrono = { version = "0.4.38", features = ["serde"] }
enumn = "0.1.14"
env_logger = "0.11.5"
hmac = { version = "0.12.1" }
http = { version = "1.1.0" }
md-5 = "0.10.6"
regex = "1.11.0"
reqwest = { version = "0.12.8", default-features = false, features = [
	"default-tls",
	"socks",
	"stream",
] }
sea-orm = { version = "1", features = [
	"debug-print",
	"runtime-tokio-native-tls",
	"sqlx-sqlite",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.34"
serde_urlencoded = "0.7"
sha2 = { version = "0.10.8", default-features = false }
test-log = { version = "0.2.16", features = ["trace"] }
thiserror = "1.0.64"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
tracing = "0.1"
tracing-appender = "0.2"
tracing-log = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.11.0", features = ["v4", "fast-rng"] }
zip-extract = { version = "0.2.1" }

[dev-dependencies]
memory-stats = "1"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# bin
[profile.release]
debug = false
strip = "debuginfo"
lto = true
opt-level = "s"

# build = "build.rs"

# For testing

[[example]]
name = "model_loader"
path = "tests/model/load.rs"
doc-scrape-examples = true

[[example]]
name = "bootstrap_download"
path = "tests/bootstrap/download.rs"
doc-scrape-examples = true

[[example]]
name = "kache_test"
path = "tests/kache/test.rs"
doc-scrape-examples = true

[package.metadata.example.model_loader]
hidden = true
