# where to store the user data
workspace_root = ".data"
# path to the game cache directory
cache_root = "./z/cache"
# path the the game resource mods directory
mods_root = "./z/mods"
# the hostname or ip address to listen for connections on
bind = "0.0.0.0:27666"
# the proxy to use for fetch missing game resources
proxy = "socks5://127.0.0.1:1086"
# html gadgets
gadgets_cdn = ["w00g.kancolle-server.com", "kcwiki.github.io/cache"]
# game resources
game_cdn = [
	"w01y.kancolle-server.com",
	"w02k.kancolle-server.com",
	"w03s.kancolle-server.com",
	"w04m.kancolle-server.com",
	"w05o.kancolle-server.com",
	"w06t.kancolle-server.com",
	"w07l.kancolle-server.com",
	"w08r.kancolle-server.com",
	"w09s.kancolle-server.com",
	"w10b.kancolle-server.com",
	"w11t.kancolle-server.com",
	"w12p.kancolle-server.com",
	"w13b.kancolle-server.com",
	"w14h.kancolle-server.com",
	"w15p.kancolle-server.com",
	"w16s.kancolle-server.com",
	"w17k.kancolle-server.com",
	"w18i.kancolle-server.com",
	"w19s.kancolle-server.com",
	"w20h.kancolle-server.com",
]
