[package]
name = "emukc_dylib"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
emukc_internal = { path = "../emukc_internal" }

[lints]
workspace = true
