[package]
name = "emukc_macros"
version = "0.1.0"
edition = "2021"
description = "Provides macros for the emukc project"

[lib]
proc-macro = true

[dependencies]

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options"]
all-features = true
