#![allow(missing_docs)]

use super::map::MapCatalog;

/// Generated by `cargo run --example tsunkit_map_codegen -- <input.json>`.
///
/// Empty by default; runtime falls back to `kc_data` or manifest-derived maps.
pub const GENERATED_MAP_CATALOG_JSON: &str = "";

pub fn load() -> Option<MapCatalog> {
	let raw = GENERATED_MAP_CATALOG_JSON.trim();
	if raw.is_empty() {
		return None;
	}
	serde_json::from_str(raw).ok()
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn empty_generated_catalog_returns_none() {
		assert!(load().is_none());
	}
}
