//! Example: work with Tsunkit map cache, normalized JSON, and baked Rust output.

use std::{collections::BTreeSet, fs, path::Path, path::PathBuf, str::FromStr};

use clap::{Args, Parser, Subcommand};
use emukc::model::codex::map::MapCatalog;
use emukc::prelude::*;

#[derive(Parser, Debug)]
#[command(
	name = "tsunkit_map_data_downloader",
	about = "Tsunkit map tool: sync cache, normalize JSON, and generate baked Rust",
	long_about = "Work with Tsunkit-derived map data in three stages:\n\n1. sync       Refresh local cache from Tsunkit (best effort)\n2. normalize  Turn local cache into normalized MapCatalog JSON\n3. codegen    Turn normalized JSON into generated Rust\n4. bake       Run normalize + codegen in one command\n\nRecommended if you already have local cache:\n  cargo run --example tsunkit_map_data_downloader -- bake\n\nRecommended if you want to probe one map online:\n  cargo run --example tsunkit_map_data_downloader -- sync --map 1-1"
)]
struct Cli {
	#[command(subcommand)]
	command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
	/// Read existing `.data/temp/tsunkit_nav` cache and write normalized JSON.
	Normalize(PathsArgs),
	/// Refresh map cache from Tsunkit before writing normalized JSON.
	Sync(SyncArgs),
	/// Generate `generated_map_catalog.rs` from normalized JSON.
	Codegen(CodegenArgs),
	/// Normalize local cache and immediately generate baked Rust output.
	Bake(BakeArgs),
}

#[derive(Args, Debug)]
struct PathsArgs {
	/// Directory containing `start2.json` and the `tsunkit_nav/` cache directory.
	#[arg(long, default_value = ".data/temp", value_name = "DIR")]
	data_root: PathBuf,

	/// Output path for the normalized `MapCatalog` JSON file.
	#[arg(long, default_value = ".data/generated/tsunkit_map_catalog.json", value_name = "FILE")]
	output: PathBuf,
}

#[derive(Args, Debug)]
struct SyncArgs {
	#[command(flatten)]
	paths: PathsArgs,

	/// Proxy URL used for Tsunkit requests.
	#[arg(long, value_name = "URL")]
	proxy: Option<String>,

	/// Overwrite existing files under `<data-root>/tsunkit_nav`.
	#[arg(long)]
	overwrite: bool,

	/// Limit sync to one or more map IDs, e.g. `1-1` or `57-3`.
	#[arg(long = "map", value_name = "MAP")]
	maps: Vec<String>,

	/// Maximum number of concurrent requests.
	#[arg(long, default_value_t = 2)]
	concurrent: usize,

	/// Also fetch `/nodesummary` responses. Disabled by default because the endpoint is slow/unreliable.
	#[arg(long)]
	include_nodesummaries: bool,

	/// Also fetch `/enemycomps` responses. Disabled by default because the endpoint is slow/unreliable.
	#[arg(long)]
	include_enemycomps: bool,
}

#[derive(Args, Debug)]
struct CodegenArgs {
	/// Input JSON created by `normalize` or `sync`.
	#[arg(long, default_value = ".data/generated/tsunkit_map_catalog.json", value_name = "FILE")]
	input: PathBuf,

	/// Output Rust module that will be checked into the repository.
	#[arg(
		long,
		default_value = "crates/emukc_model/src/codex/generated_map_catalog.rs",
		value_name = "FILE"
	)]
	output: PathBuf,
}

#[derive(Args, Debug)]
struct BakeArgs {
	#[command(flatten)]
	paths: PathsArgs,

	/// Output Rust module that will be checked into the repository.
	#[arg(
		long,
		default_value = "crates/emukc_model/src/codex/generated_map_catalog.rs",
		value_name = "FILE"
	)]
	rust_output: PathBuf,
}

fn read_manifest(data_root: &Path) -> emukc::model::kc2::start2::ApiManifest {
	let manifest_path = data_root.join("start2.json");
	let manifest_raw = fs::read_to_string(&manifest_path).expect("failed to read start2.json");
	emukc::model::kc2::start2::ApiManifest::from_str(&manifest_raw).expect("invalid start2")
}

fn normalize_catalog(paths: &PathsArgs) -> MapCatalog {
	let manifest = read_manifest(&paths.data_root);
	parse_tsunkit_nav(paths.data_root.join("tsunkit_nav"), &manifest)
		.expect("failed to parse tsunkit_nav")
}

fn write_catalog_json(catalog: &MapCatalog, output: &Path) {
	if let Some(parent) = output.parent() {
		fs::create_dir_all(parent).expect("failed to create output dir");
	}
	fs::write(output, serde_json::to_string_pretty(catalog).unwrap())
		.expect("failed to write normalized map catalog");
}

fn generate_rust_module(input: &Path, output: &Path) {
	let raw = fs::read_to_string(input).expect("failed to read normalized map catalog json");
	let _: MapCatalog = serde_json::from_str(&raw).expect("invalid normalized map catalog json");

	let content = format!(
		"#![allow(missing_docs)]\n\nuse super::map::MapCatalog;\n\n/// Generated by `cargo run --example tsunkit_map_data_downloader -- codegen --input {input}`.\npub const GENERATED_MAP_CATALOG_JSON: &str = r####\"{json}\"####;\n\npub fn load() -> Option<MapCatalog> {{\n\tserde_json::from_str(GENERATED_MAP_CATALOG_JSON).ok()\n}}\n\n#[cfg(test)]\nmod tests {{\n\tuse super::*;\n\n\t#[test]\n\tfn generated_catalog_is_valid_json() {{\n\t\tassert!(load().is_some());\n\t}}\n}}\n",
		input = input.display(),
		json = raw
	);

	if let Some(parent) = output.parent() {
		fs::create_dir_all(parent).expect("failed to create output dir");
	}
	fs::write(output, content).expect("failed to write generated Rust module");
}

async fn run_sync(sync: &SyncArgs) -> TsunkitNavDownloadStats {
	let map_filter = if sync.maps.is_empty() {
		None
	} else {
		Some(sync.maps.iter().cloned().collect::<BTreeSet<_>>())
	};

	let stats = download_tsunkit_nav_with_options(
		&sync.paths.data_root,
		sync.overwrite,
		sync.proxy.as_deref(),
		TsunkitNavDownloadOptions {
			concurrent: Some(sync.concurrent),
			map_filter,
			fetch_nodesummaries: sync.include_nodesummaries,
			fetch_enemycomps: sync.include_enemycomps,
		},
	)
	.await
	.expect("failed to download tsunkit_nav");

	if stats.failures > 0 {
		eprintln!(
			"note: sync completed with {} fetch failures. Tsunkit is currently flaky; retry with `--map <MAP>` for a smaller scope, or use `normalize` on existing cache.",
			stats.failures,
		);
	}

	stats
}

#[tokio::main]
async fn main() {
	let _guard = new_log_builder().with_log_level("info").build();
	let cli = Cli::parse();

	match cli.command {
		Command::Normalize(paths) => {
			let catalog = normalize_catalog(&paths);
			write_catalog_json(&catalog, &paths.output);
			println!(
				"wrote {} maps to {} (mode=normalize)",
				catalog.maps.len(),
				paths.output.display()
			);
		}
		Command::Sync(sync) => {
			let stats = run_sync(&sync).await;
			let catalog = normalize_catalog(&sync.paths);
			write_catalog_json(&catalog, &sync.paths.output);
			println!(
				"wrote {} maps to {} (downloaded maps={}, nodesummaries={}, enemycomps={}, failures={}, mode=sync)",
				catalog.maps.len(),
				sync.paths.output.display(),
				stats.maps,
				stats.nodesummaries,
				stats.enemycomps,
				stats.failures,
			);
		}
		Command::Codegen(args) => {
			generate_rust_module(&args.input, &args.output);
			println!("wrote {}", args.output.display());
		}
		Command::Bake(args) => {
			let catalog = normalize_catalog(&args.paths);
			write_catalog_json(&catalog, &args.paths.output);
			generate_rust_module(&args.paths.output, &args.rust_output);
			println!(
				"wrote {} maps to {} and baked Rust to {} (mode=bake)",
				catalog.maps.len(),
				args.paths.output.display(),
				args.rust_output.display(),
			);
		}
	}
}
