[package]
name = "emukc_gameplay"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
# emukc
emukc_crypto = { path = "../emukc_crypto" }
emukc_db = { path = "../emukc_db" }
emukc_model = { path = "../emukc_model" }
emukc_time = { path = "../emukc_time" }

# other
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
